title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

nav:
  - name: "Home"
    link: "/"
  - name: "Research"
    link: "/research"
  - name: "Teaching"
    link: "/teaching"
  - name: "Notes"
    link: "/notes"
  - name: "CV"
    link: "/cv"
  - name: "Contact"
    link: "/contact"
