title: "Kaden Saucedo"
description: "Mathematics PhD student at the University of Georgia studying algebraic geometry."
author: "Kaden Saucedo"


theme: minima

# These are the pages that will appear in the top navigation bar.
header_pages:
  - index.md
  - research.md
  - teaching.md
  - notes.md
  - cv.md
  - contact.md
