title: "Kaden Saucedo"
description: "Algebraic geometry and moduli of surfaces"

theme: minima

# These are the pages that will appear in the top navigation bar.
header_pages:
  - index.md
  - research.md
  - teaching.md
  - notes.md
  - cv.md
  - contact.md
